name: dolla-consensus-base
version: 1.0.0
synopsis: Librairies used to support the consensus microservices.
description: This package contains all the functionalities commonly used accross the different microservices of the
             consensus algorithm.
maintainer: maintainer@dolla.com
github: dolla-consortium/consensus-base
category:   Consortium Blockchain
copyright:  2020 Dolla
license:    BSD-3-Clause
license-file: LICENSE
extra-source-files:
  - README.md

dependencies:
  - dolla-base == 1.0.0
  - base == 4.13.0.0

ghc-options:
  - -Wall

library:
  verbatim:
    autogen-modules: Paths_dolla_consensus_base

  source-dirs: lib

  dependencies:
    - containers == 0.6.2.1
    - text == 1.2.4.0
    - mtl == 2.2.2
    - aeson == 1.4.7.1
    - uuid  == 1.3.13
    - streamly == 0.7.2
    - unordered-containers == 0.2.10.0
    - hashable == 1.3.0.0
    - directory == 1.3.6.0
    - bytestring == 0.10.10.0
    - concurrent-extra == 0.7.0.12
    - interpolatedstring-perl6 == 1.0.2
    - eventstore == 1.4.1
    - mmorph == 1.1.3
    - fsnotify == 0.3.0.1
    - exceptions == 0.10.4
    - binary == 0.8.7.0
    - streamly-fsnotify == 1.1.1.0

tests:
  dolla-consensus-base-test:
    main:   Spec.hs
    source-dirs: test

    ghc-options:
      - -threaded
    dependencies:
      - dolla-consensus-base
      - hspec
      - QuickCheck
      - quickcheck-instances
      - streamly == 0.7.2
      - containers == 0.6.2.1
      - unordered-containers == 0.2.10.0
      - mtl == 2.2.2
      - mmorph == 1.1.3
      - aeson == 1.4.7.1
      - interpolatedstring-perl6 == 1.0.2
      - uuid == 1.3.13
    verbatim:
      build-tool-depends: "hspec-discover:hspec-discover"
